name: Facebook
package-name: aldryn-facebook
url: https://github.com/aldryn/aldryn-facebook
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - aldryn_facebook
version: 0.0.4
description: Collection of Facebook social plugins.
license:
  name: BSD
  text: !literal-include LICENSE.txt
